apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: {{ .Release.Name | printf "%s{{name}}"}}{{ .Release.Name | printf "%s{{name}}" | sha256sum | trunc 4 }}
    spec:
      project: "{{ .Values.template.project }}"
      source:
        repoURL: {{ .Values.template.source.repoURL }}
        targetRevision: {{ .Values.template.source.targetRevision }}
        path: {{ .Values.template.source.path }}
        name: {{.Release.Name}}{{ printf "{{name}}"}}
        test: {{ .Release.Name | printf "%s{{name}}"}}{{ .Release.Name | printf "%s{{name}}" | sha256sum | trunc 4 }}
      destination:
        server: {{ printf "'{{%s}}'" .Values.template.destination.server }}
        namespace: {{ .Values.template.destination.namespace }}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true